## classification case ##

**importing libraries**

In [1]:
import numpy as np
import pandas as pd

In [2]:
import tensorflow as tf

**preprocessing**

In [3]:
dataset = pd.read_csv('Churn_Modelling.csv')
x=dataset.iloc[:,3:-1].values
y=dataset.iloc[:,-1].values
x

array([[619, 'France', 'Female', ..., 1, 1, 101348.88],
       [608, 'Spain', 'Female', ..., 0, 1, 112542.58],
       [502, 'France', 'Female', ..., 1, 0, 113931.57],
       ...,
       [709, 'France', 'Female', ..., 0, 1, 42085.58],
       [772, 'Germany', 'Male', ..., 1, 0, 92888.52],
       [792, 'France', 'Female', ..., 1, 0, 38190.78]], dtype=object)

In [12]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [1])], remainder='passthrough')
x=np.array(ct.fit_transform(x))
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [154]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
x[:,4]=le.fit_transform(x[:,4])
x

array([[1.0, 0.0, 0.0, ..., 1, 1, 101348.88],
       [0.0, 0.0, 1.0, ..., 0, 1, 112542.58],
       [1.0, 0.0, 0.0, ..., 1, 0, 113931.57],
       ...,
       [1.0, 0.0, 0.0, ..., 0, 1, 42085.58],
       [0.0, 1.0, 0.0, ..., 1, 0, 92888.52],
       [1.0, 0.0, 0.0, ..., 1, 0, 38190.78]], dtype=object)

In [155]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train , y_test = train_test_split(x,y,test_size=0.2, random_state=0)

In [156]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x_train = sc.fit_transform(x_train)
x_test=sc.transform(x_test)

***we have to encode every data while performing deep learning***

In [157]:
x_train

array([[-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
        -1.03227043,  1.10643166],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
         0.9687384 , -0.74866447],
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.48533467],
       ...,
       [ 0.98560362, -0.5698444 , -0.57369368, ...,  0.64259497,
        -1.03227043,  1.41231994],
       [-1.01460667, -0.5698444 ,  1.74309049, ...,  0.64259497,
         0.9687384 ,  0.84432121],
       [-1.01460667,  1.75486502, -0.57369368, ...,  0.64259497,
        -1.03227043,  0.32472465]])

## building ANN ##

initialising ANN

In [158]:
ann = tf.keras.models.Sequential()

adding the input layer and first hidden layer

In [159]:
ann.add(tf.keras.layers.Dense(units =6,activation ='relu'))

adding second hidden layer

In [160]:
ann.add(tf.keras.layers.Dense(units =6,activation ='relu'))

adding output layer

we are not using threshold function because we need probability
if we need prediction either 1 or 0 we can use threshold function

In [161]:
ann.add(tf.keras.layers.Dense(units =1,activation ='sigmoid'))

### training the ANN ###

compiling ANN

In [162]:
ann.compile(optimizer ='adam' , loss = 'binary_crossentropy', metrics=['accuracy'] )

if we are dealing with categorical data we then loss function = 'catogorical_crossentropy' and activation should be "softmax" not sigmoid

training the ann

In [163]:
ann.fit(x_train, y_train, batch_size =32, epochs =100)

Epoch 1/100
250/250 [==============================] - 1s 1ms/step - loss: 0.5089 - accuracy: 0.7960
Epoch 2/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4522 - accuracy: 0.7960
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4381 - accuracy: 0.7960
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4316 - accuracy: 0.7960
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 0.4276 - accuracy: 0.7960
Epoch 6/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4253 - accuracy: 0.7960
Epoch 7/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4232 - accuracy: 0.7969
Epoch 8/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4214 - accuracy: 0.8009
Epoch 9/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4195 - accuracy: 0.8096
Epoch 10/100
250/250 [==============================] - 0s 1ms/step - loss: 0.4180 - accura

#### predicting result for single observation ####

Homework
Use our ANN model to predict if the customer with the following informations will leave the bank:
Geography: France
Credit Score: 600
Gender: Male
Age: 40 years old
Tenure: 3 years
Balance: <latex iconid=‘0’> 50000
So, should we say goodbye to that customer ?

In [142]:
new_x = [[600,'France','Male',40,3,60000,2,1,1,50000]]
new_x



[[600, 'France', 'Male', 40, 3, 60000, 2, 1, 1, 50000]]

In [143]:
new_x=np.array(ct.fit_transform(new_x))
new_x

array([[1.0, 600, 'Male', 40, 3, 60000, 2, 1, 1, 50000]], dtype=object)

In [144]:
new_x[:,2]=le.fit_transform(new_x[:,2])
new_x

array([[1.0, 600, 0, 40, 3, 60000, 2, 1, 1, 50000]], dtype=object)

In [6]:
new_x=sc.transform(new_x)
new_x

NameError: name 'sc' is not defined

In [126]:
ann.predict(new_x)>0.5

ValueError: in user code:

    File "C:\Users\dheer\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\training.py", line 1801, in predict_function  *
        return step_function(self, iterator)
    File "C:\Users\dheer\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\training.py", line 1790, in step_function  **
        outputs = model.distribute_strategy.run(run_step, args=(data,))
    File "C:\Users\dheer\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\training.py", line 1783, in run_step  **
        outputs = model.predict_step(data)
    File "C:\Users\dheer\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\training.py", line 1751, in predict_step
        return self(x, training=False)
    File "C:\Users\dheer\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\utils\traceback_utils.py", line 67, in error_handler
        raise e.with_traceback(filtered_tb) from None
    File "C:\Users\dheer\AppData\Local\Programs\Python\Python310\lib\site-packages\keras\engine\input_spec.py", line 248, in assert_input_compatibility
        raise ValueError(

    ValueError: Exception encountered when calling layer "sequential_1" (type Sequential).
    
    Input 0 of layer "dense_1" is incompatible with the layer: expected axis -1 of input shape to have value 12, but received input with shape (None, 10)
    
    Call arguments received:
      • inputs=tf.Tensor(shape=(None, 10), dtype=float32)
      • training=False
      • mask=None
