In [1]:
import pandas as pd
import numpy as np
import tensorflow as tf

In [2]:
dataset = pd.read_excel('Folds5x2_pp.xlsx')
dataset

AT      V       AP     RH      PE
0     14.96  41.76  1024.07  73.17  463.26
1     25.18  62.96  1020.04  59.08  444.37
2      5.11  39.40  1012.16  92.14  488.56
3     20.86  57.32  1010.24  76.64  446.48
4     10.82  37.50  1009.23  96.62  473.90
...     ...    ...      ...    ...     ...
9563  16.65  49.69  1014.01  91.00  460.03
9564  13.19  39.18  1023.67  66.78  469.62
9565  31.32  74.33  1012.92  36.48  429.57
9566  24.48  69.45  1013.86  62.39  435.74
9567  21.60  62.52  1017.23  67.87  453.28

[9568 rows x 5 columns]

In [3]:
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values


In [19]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test =train_test_split(x,y,test_size=0.2, random_state=0)
print(x_test)

[[  28.66   77.95 1009.56   69.07]
 [  17.48   49.39 1021.51   84.53]
 [  14.86   43.14 1019.21   99.14]
 ...
 [  12.24   44.92 1023.74   88.21]
 [  27.28   47.93 1003.46   59.22]
 [  17.28   39.99 1007.09   74.25]]


In [5]:
# from sklearn.preprocessing import StandardScaler
# sc_x = StandardScaler()
# x_train = sc_x.fit_transform(x_train)
# x_test = sc_x.transform(x_test)
# sc_y = StandardScaler()
# y_train = sc_y.fit_transform(y_train.reshape(len(y_train),1))
# y_test=sc_y.transform(y_test.reshape(len(y_test),1))

In [6]:
y_train

array([473.93, 467.87, 431.97, ..., 459.01, 462.72, 428.12])

In [7]:
y_test

array([431.23, 460.01, 461.14, ..., 473.26, 438.  , 463.28])

In [8]:
ann = tf.keras.models.Sequential()

In [9]:
ann.add(tf.keras.layers.Dense(units =6, activation='relu'))

In [10]:
ann.add(tf.keras.layers.Dense(units=6, activation ='relu'))

you can remove the activation function for regression for better results

In [11]:
ann.add(tf.keras.layers.Dense(units=1))

In [12]:
ann.compile(optimizer='adam', loss='mean_squared_error')

In [13]:
ann.fit(x_train, y_train, batch_size=32, epochs=100)

Epoch 1/100
240/240 [==============================] - 1s 1ms/step - loss: 291420.2500
Epoch 2/100
240/240 [==============================] - 0s 1ms/step - loss: 211001.9062
Epoch 3/100
240/240 [==============================] - 0s 1ms/step - loss: 146406.6719
Epoch 4/100
240/240 [==============================] - 0s 1ms/step - loss: 11255.0254
Epoch 5/100
240/240 [==============================] - 0s 1ms/step - loss: 475.1888
Epoch 6/100
240/240 [==============================] - 0s 1ms/step - loss: 463.4373
Epoch 7/100
240/240 [==============================] - 0s 1ms/step - loss: 450.2300
Epoch 8/100
240/240 [==============================] - 0s 1ms/step - loss: 435.3968
Epoch 9/100
240/240 [==============================] - 0s 1ms/step - loss: 418.9977
Epoch 10/100
240/240 [==============================] - 0s 1ms/step - loss: 400.9201
Epoch 11/100
240/240 [==============================] - 0s 1ms/step - loss: 381.3286
Epoch 12/100
240/240 [==============================] - 0s 1ms/

In [14]:
y_predict = ann.predict(x_test)
np.concatenate((y_predict.reshape(len(y_predict),1),y_test.reshape(len(y_test),1)),1)

array([[430.38458252, 431.23      ],
       [461.98184204, 460.01      ],
       [464.83718872, 461.14      ],
       ...,
       [472.87893677, 473.26      ],
       [439.33758545, 438.        ],
       [458.79946899, 463.28      ]])

In [30]:
ann.predict([[15,41,1025,70]])

array([[471.38623]], dtype=float32)