In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
dataset = pd.read_csv('Data.csv')
print(dataset)

         AT      V       AP     RH      PE
0     14.96  41.76  1024.07  73.17  463.26
1     25.18  62.96  1020.04  59.08  444.37
2      5.11  39.40  1012.16  92.14  488.56
3     20.86  57.32  1010.24  76.64  446.48
4     10.82  37.50  1009.23  96.62  473.90
...     ...    ...      ...    ...     ...
9563  16.65  49.69  1014.01  91.00  460.03
9564  13.19  39.18  1023.67  66.78  469.62
9565  31.32  74.33  1012.92  36.48  429.57
9566  24.48  69.45  1013.86  62.39  435.74
9567  21.60  62.52  1017.23  67.87  453.28

[9568 rows x 5 columns]


In [3]:
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values
print(x)
print(y)

[[  14.96   41.76 1024.07   73.17]
 [  25.18   62.96 1020.04   59.08]
 [   5.11   39.4  1012.16   92.14]
 ...
 [  31.32   74.33 1012.92   36.48]
 [  24.48   69.45 1013.86   62.39]
 [  21.6    62.52 1017.23   67.87]]
[463.26 444.37 488.56 ... 429.57 435.74 453.28]


In [4]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2, random_state=0)

In [5]:
from sklearn.tree import DecisionTreeRegressor
regressor =DecisionTreeRegressor()
regressor.fit(x_train, y_train)

DecisionTreeRegressor()

In [6]:
y_predict = regressor.predict(x_test)
print(y_predict)
print(y_test)

[429.06 459.59 460.19 ... 471.46 437.76 462.55]
[431.23 460.01 461.14 ... 473.26 438.   463.28]


In [7]:
regressor.predict([[25.18 ,  62.96, 1020.04,   59.08]])

array([444.37])

In [8]:
print(np.concatenate((y_test.reshape(len(y_test),1), y_predict.reshape(len(y_predict),1)),1))

[[431.23 429.06]
 [460.01 459.59]
 [461.14 460.19]
 ...
 [473.26 471.46]
 [438.   437.76]
 [463.28 462.55]]


In [9]:
from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_predict)
r2

0.9218763764247412