In [14]:
import numpy as np
import pandas as pd

In [15]:
dataset = pd.read_csv('Data.csv')
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values

In [16]:
from sklearn.model_selection import train_test_split
x_train,x_test, y_train, y_test=train_test_split(x,y, test_size=0.2, random_state=0)

In [17]:
from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression()

In [18]:
y_predict=regressor.predict(x_test)
y_predict

array([431.42761597, 458.56124622, 462.75264705, ..., 469.51835895,
       442.41759454, 461.88279939])

In [19]:
y_test

array([431.23, 460.01, 461.14, ..., 473.26, 438.  , 463.28])

In [20]:
np.concatenate((y_predict.reshape(len(y_predict),1),y_test.reshape(len(y_test),1)),1)

array([[431.42761597, 431.23      ],
       [458.56124622, 460.01      ],
       [462.75264705, 461.14      ],
       ...,
       [469.51835895, 473.26      ],
       [442.41759454, 438.        ],
       [461.88279939, 463.28      ]])

In [21]:
from sklearn.metrics import r2_score
r2=r2_score(y_test,y_predict)
r2

0.9325315554761303

In [22]:
n=40
k=2
adj_r2_score = 1 - ((1-r2)*(n-1)/(n-k-1))
adj_r2_score

0.9288846125288941