In [1]:
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv('Data.csv')
x=dataset.iloc[:, :-1].values
y=dataset.iloc[:,-1].values

In [3]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test=train_test_split(x,y,test_size=0.2, random_state=0)

In [4]:
from sklearn.ensemble import RandomForestRegressor
regressor = RandomForestRegressor(n_estimators= 10, random_state=0)
regressor.fit(x_train, y_train)

RandomForestRegressor(n_estimators=10, random_state=0)

In [5]:
y_predict = regressor.predict(x_test)
y_predict

array([434.049, 458.785, 463.02 , ..., 469.479, 439.566, 460.385])

In [6]:
y_test

array([431.23, 460.01, 461.14, ..., 473.26, 438.  , 463.28])

In [7]:
np.concatenate((x_test,y_predict.reshape(len(y_predict),1), y_test.reshape(len(y_test),1)),1)

array([[  28.66 ,   77.95 , 1009.56 ,   69.07 ,  434.049,  431.23 ],
       [  17.48 ,   49.39 , 1021.51 ,   84.53 ,  458.785,  460.01 ],
       [  14.86 ,   43.14 , 1019.21 ,   99.14 ,  463.02 ,  461.14 ],
       ...,
       [  12.24 ,   44.92 , 1023.74 ,   88.21 ,  469.479,  473.26 ],
       [  27.28 ,   47.93 , 1003.46 ,   59.22 ,  439.566,  438.   ],
       [  17.28 ,   39.99 , 1007.09 ,   74.25 ,  460.385,  463.28 ]])

In [8]:
from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_predict)
r2

0.9615908334363876