In [1]:
import numpy as np
import pandas as pd

data pre processing

In [2]:
dataset = pd.read_csv('Data.csv')
x=dataset.iloc[:,:-1].values
y=dataset.iloc[:,-1].values


scaling as it is support vector regression

In [3]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test= train_test_split(x,y,test_size=0.2, random_state=0)
y_train=y_train.reshape(len(y_train), 1)
print(y_train)

[[473.93]
 [467.87]
 [431.97]
 ...
 [459.01]
 [462.72]
 [428.12]]


In [4]:
from sklearn.preprocessing import StandardScaler
sc_x = StandardScaler()
sc_y = StandardScaler()
x_train=sc_x.fit_transform(x_train)
y_train=sc_y.fit_transform(y_train)
print(y_train)


[[ 1.15069786]
 [ 0.79540777]
 [-1.30936356]
 ...
 [ 0.27595724]
 [ 0.49346982]
 [-1.53508417]]


In [5]:
from sklearn.svm import SVR
regressor = SVR(kernel='rbf')
regressor.fit(x_train, y_train)

C:\Users\dheer\anaconda3\lib\site-packages\sklearn\utils\validation.py:63: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  return f(*args, **kwargs)


SVR()

In [6]:
y_predict = regressor.predict(sc_x.fit_transform(x_test))

y_predict=sc_y.inverse_transform(y_predict)
(y_predict)

array([434.49984934, 457.70985097, 460.84909947, ..., 470.22304261,
       439.28872637, 460.42910288])

In [7]:
(y_test)


array([431.23, 460.01, 461.14, ..., 473.26, 438.  , 463.28])

In [8]:
np.concatenate((y_test.reshape(len(y_test),1),y_predict.reshape(len(y_predict),1)),1)

array([[431.23      , 434.49984934],
       [460.01      , 457.70985097],
       [461.14      , 460.84909947],
       ...,
       [473.26      , 470.22304261],
       [438.        , 439.28872637],
       [463.28      , 460.42910288]])

In [9]:
from sklearn.metrics import r2_score

r2 = r2_score(y_test, y_predict)
r2

0.9483693304317926